# Generated by Django 2.2.5 on 2020-02-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetable',
            name='filename',
            field=models.CharField(default='NOT SPECIFIED', max_length=256),
        ),
    ]
