# Generated by Django 2.2.5 on 2020-02-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_filetable_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetable',
            name='filename',
        ),
    ]
